### ISSUE TITLE
Broken for negative positions

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-chunk#11]
```
buffer.js:580
    throw new RangeError('offset is not uint');
    ^
RangeError: offset is not uint
    at checkOffset (buffer.js:580:11)
    at Buffer.readUInt16LE (buffer.js:609:5)
    at Chunk.getBlockData (/media/documents/Documents/programmation/interlangage/minecraft/craftyjs/node_modules/prismarine-chunk/dist/chunk.js:82:34)
    at Chunk.setBlockType (/media/documents/Documents/programmation/interlangage/minecraft/craftyjs/node_modules/prismarine-chunk/dist/chunk.js:106:33)
    at inject (/media/documents/Documents/programmation/interlangage/minecraft/craftyjs/lib/serverPlugins/world.js:23:22)
    at MCServer.connect (/media/documents/Documents/programmation/interlangage/minecraft/craftyjs/index.js:31:30)
    at Object.createMCServer (/media/documents/Documents/programmation/interlangage/minecraft/craftyjs/index.js:16:12)
    at Object.<anonymous> (/media/documents/Documents/programmation/interlangage/minecraft/craftyjs/app.js:15:10)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:312:12)
```

**Comment by rom1504** [comment]
nevermind, this is prismarine-chunk not primarine-world
