### ISSUE TITLE
Error reading direct palettes for 1.18

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/prismarine-chunk#164]
```
Error: Attempted to read beyond the bounds of the managed data.
    at SmartBuffer.ensureReadable (C:\Users\---\Documents\js-projects\my-bot\node_modules\smart-buffer\build\smartbuffer.js:1093:19)
    at SmartBuffer._readNumberValue (C:\Users\---\Documents\js-projects\my-bot\node_modules\smart-buffer\build\smartbuffer.js:1163:14)
    at SmartBuffer.readUInt32BE (C:\Users\---\Documents\js-projects\my-bot\node_modules\smart-buffer\build\smartbuffer.js:361:21)
    at BitArray.readBuffer (C:\Users\---\Documents\js-projects\my-bot\node_modules\prismarine-chunk\src\pc\common\BitArrayNoSpan.js:183:34)
    at DirectPaletteContainer.readBuffer (C:\Users\---\Documents\js-projects\my-bot\node_modules\prismarine-chunk\src\pc\common\PaletteContainer.js:30:15)
    at Function.read (C:\Users\---\Documents\js-projects\my-bot\node_modules\prismarine-chunk\src\pc\common\PaletteChunkSection.js:96:12)
    at ChunkColumn.load (C:\Users\---\Documents\js-projects\my-bot\node_modules\prismarine-chunk\src\pc\1.18\ChunkColumn.js:242:41)
    at addColumn (C:\Users\---\Documents\js-projects\my-bot\node_modules\mineflayer\lib\plugins\blocks.js:99:14)
    at Client.<anonymous> (C:\Users\---\Documents\js-projects\my-bot\node_modules\mineflayer\lib\plugins\blocks.js:319:5)
    at Client.emit (node:events:394:28)
```

**Comment by rom1504** [comment]
when

**Comment by MetuMortis-code** [comment]
on joining server

**Comment by u9g** [comment]
still getting ```
RangeError: Invalid typed array length: Infinity
    at new Uint32Array (<anonymous>)
    at new BitArray (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\common\BitArrayNoSpan.js:16:17)
    at new DirectPaletteContainer (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\common\PaletteContainer.js:8:17)
    at Function.read (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\common\PaletteChunkSection.js:109:15)
    at ChunkColumn.load (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\1.18\ChunkColumn.js:246:41)
    at addColumn (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\mineflayer\lib\plugins\blocks.js:57:14)
    at Client.<anonymous> (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\mineflayer\lib\plugins\blocks.js:272:5)
    at Client.emit (node:events:394:28)
    at FullPacketParser.<anonymous> (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:394:28)
RangeError: Invalid typed array length: Infinity
    at new Uint32Array (<anonymous>)
    at new BitArray (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\common\BitArrayNoSpan.js:16:17)
    at new DirectPaletteContainer (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\common\PaletteContainer.js:8:17)
    at Function.read (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\common\PaletteChunkSection.js:109:15)
    at ChunkColumn.load (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\prismarine-chunk\src\pc\1.18\ChunkColumn.js:246:41)
    at addColumn (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\mineflayer\lib\plugins\blocks.js:57:14)
    at Client.<anonymous> (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\mineflayer\lib\plugins\blocks.js:272:5)
    at Client.emit (node:events:394:28)
    at FullPacketParser.<anonymous> (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:394:28)
Waiting for the debugger to disconnect...
C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\mineflayer\lib\plugins\blocks.js:294
          column.setBlockEntity(blockEntity, blockEntity.nbtData)
                 ^

TypeError: Cannot read property 'setBlockEntity' of undefined
    at Client.<anonymous> (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\mineflayer\lib\plugins\blocks.js:294:18)
    at Client.emit (node:events:394:28)
    at FullPacketParser.<anonymous> (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:394:28)
    at addChunk (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\protodef\src\serializer.js:89:10)
    at FullPacketParser.Transform._read (C:\Users\Jason\Documents\js-projects\docs-bot\node_modules\readable-stream\lib\_stream_transform.js:177:10)
```
on connecting to `hypixel.net`

**Comment by nickelpro** [comment]
Would be useful to get a dump of a failing chunk

**Comment by PiggyAwesome** [comment]
Hi, did someone fix this yet?
