### ISSUE TITLE
RangeError: Invalid typed array length: Infinity

### ISSUE THREAD

**Issue by hazysu** [PrismarineJS/prismarine-chunk#169]
I'm getting the following error:
```
/home/hazy/Documents/Projects/mncrft/node_modules/prismarine-chunk/src/pc/common/BitArrayNoSpan.js:16
    this.data = new Uint32Array(options?.data ?? bufferSize)
                ^

RangeError: Invalid typed array length: Infinity
    at new Uint32Array (<anonymous>)
    at new BitArray (/home/hazy/Documents/Projects/mncrft/node_modules/prismarine-chunk/src/pc/common/BitArrayNoSpan.js:16:17)
    at new DirectPaletteContainer (/home/hazy/Documents/Projects/mncrft/node_modules/prismarine-chunk/src/pc/common/PaletteContainer.js:8:17)
    at Function.read (/home/hazy/Documents/Projects/mncrft/node_modules/prismarine-chunk/src/pc/common/PaletteChunkSection.js:109:15)
    at ChunkColumn.load (/home/hazy/Documents/Projects/mncrft/node_modules/prismarine-chunk/src/pc/1.18/ChunkColumn.js:245:41)
    at Client.<anonymous> (/home/hazy/Documents/Projects/mncrft/index.js:44:23)
    at Client.emit (node:events:390:28)
    at FullPacketParser.<anonymous> (/home/hazy/Documents/Projects/mncrft/node_modules/minecraft-protocol/src/client.js:90:12)
    at FullPacketParser.emit (node:events:390:28)
    at addChunk (/home/hazy/Documents/Projects/mncrft/node_modules/readable-stream/lib/_stream_readable.js:298:12)

Node.js v17.3.0
```
Here's my code.
```js
const prismarineChunk = require('prismarine-chunk')
const mc = require('minecraft-protocol')
const bodyParser = require('body-parser')
const express = require('express')
const app = express()
const port = 3000
const expressWs = require('express-ws')(app)

app.use(bodyParser.json())

app.ws('/', (ws, req) => {
    let client = mc.createClient({
        host: req.query.host,
        port: parseInt(req.query.port),
        username: req.query.username,
        password: req.query.password,
        auth: req.query.auth,
        version: false,
    })
    let dimensionData = {}
    let Chunk = prismarineChunk(client.version)
    client.on('packet', (packet, meta, raw) => {
        switch (meta.name) {
            case 'login':
                let dimensionKeys = Object.keys(packet.dimension.value)
                for (let i = 0; i < dimensionKeys.length; i ++) {
                    dimensionData[dimensionKeys[i]] = packet.dimension.value[dimensionKeys[i]].value
                }
                break
            case 'map_chunk':
                let chunk = new Chunk({ minY: dimensionData.min_y, worldHeight: dimensionData.height })
                chunk.load(packet.chunkData)
                console.log(chunk)
                break
            default:
                break
        }
    })
})

app.listen(port, () => {
    console.log(`Listening at http://localhost:${port}`)
})
```

I wanted to know if I am using prismarine-chunk incorrectly, or if this is a bug?

I tried looking into it, and if it helps:
in the BitArrayNoSpan.js file, I noticed the following:
```js
// assert(options.bitsPerValue > 0, 'bits per value must at least 1')
// assert(options.bitsPerValue <= 32, 'bits per value exceeds 32')
```
In case it might help, I checked if both of these conditions were true.
bufferSize is Infinity, valuesPerLong is 0, options.capacity is 4096, and options.bitsPerValue is 102. So the first assertion is correct, but the second isn't.

**Comment by extremeheat** [comment]
Sounds like same issue as #164

**Comment by hazysu** [comment]
Ah, their reply which includes the same error message as mine was made 2 months after they initially made the issue, so when i made this issue it was not a duplicate. But yeah, theyre duplicates now.
