### ISSUE TITLE
Data buffer not correct size (was 61283, expected 61696)

### ISSUE THREAD

**Issue by cliquant** [PrismarineJS/prismarine-chunk#189]
```
[ERROR] Error: Data buffer not correct size (was 61283, expected 61696)
node:assert:123
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

666112 !== 665699

    at Client.<anonymous> (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\mineflayer\lib\plugins\blocks.js:326:12)
    at Client.emit (node:events:527:28)
    at FullPacketParser.<anonymous> (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:527:28)
    at addChunk (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\protodef\src\serializer.js:89:10)
    at FullPacketParser.Transform._read (C:\Users\nikel\OneDrive\Dators\MinecraftBot\node_modules\readable-stream\lib\_stream_transform.js:177:10) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 666112,
  expected: 665699,
  operator: 'strictEqual'
}
```

**Comment by extremeheat** [comment]
What server or world are you loading ? Can you provide steps to reproduce?
