### ISSUE TITLE
Data buffer not correct size

### ISSUE THREAD

**Issue by andre-paulo98** [PrismarineJS/prismarine-chunk#31]
Using MineFlayer to connect to a Bungee server i'm getting this crash as soon as i try to change server with command:
```
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:192
      throw(new Error(`Data buffer not correct size \(was ${data.length}, expected ${BUFFER_SIZE}\)`));
      ^

Error: Data buffer not correct size (was 164096, expected 196864)
    at Chunk.load (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:192:13)
    at addColumn (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\blocks.js:46:12)
    at Client.bot._client.on (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\blocks.js:187:7)
    at emitTwo (events.js:125:13)
    at Client.emit (events.js:213:7)
    at Parser.deserializer.on (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\node_modules\minecraft-protocol\src\client.js:102:12)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at addChunk (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_readable.js:271:11)
```
This is the code i'm using: 

```
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "server.ip",
  port: 25565,
  username: "email",
  password: "password",
  version: "1.8"
});
bot.on('spawn', function() {
    bot.chat("/server ruby");
});
```

Tried setting up a bungeecord locally with 2 servers and it worked.
Player logged in as bot has permissions to /server

**Comment by andre-paulo98** [comment]
Got a log w/ debug:
https://gist.github.com/andre-paulo98/4af6716a87f54b21dfdacb7af12b22df
