### ISSUE TITLE
PartialReadError: Read error for skyLight : undefined on Minecraft 1.10.2 when playing in the End

### ISSUE THREAD

**Issue by Roflicide** [PrismarineJS/prismarine-chunk#38]
Hi,

I've gone into the End and boxed myself into an obsidian box, and when I try to start the bot I get this error:

````
PartialReadError: Read error for skyLight : undefined
    at new ExtendableError (C:\Users\micha\node_modules\protodef\src\utils.js:75:11)
    at new PartialReadError (C:\Users\micha\node_modules\protodef\src\utils.js:81:5)
    at ProtoDef.readBuffer (C:\Users\micha\node_modules\protodef\src\datatypes\utils.js:150:42)
    at ProtoDef.read (C:\Users\micha\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Users\micha\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Users\micha\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Users\micha\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Users\micha\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (C:\Users\micha\node_modules\protodef\src\datatypes\structures.js:44:12)
````
 Running Minecraft 1.10.2 with the latest version of Mineflayer

**Comment by rom1504** [comment]
I believe this is now fixed, please try again.
