### ISSUE TITLE
TypeError: this.sections.initialize is not a function

### ISSUE THREAD

**Issue by mhsjlw** [PrismarineJS/prismarine-chunk#39]
When using `1.8.0` and using the `.initialize()` function:

```js
const chunk = new Chunk()

chunk.initialize((x, y, z, n) => {
  // Perform magic
  return block
})
```
then
```
TypeError: this.sections.initialize is not a function
    at Chunk.initialize (prismarine-chunk/src/pc/1.8/chunk.js:62:21)
```
is thrown. 

It appears that prismarine-chunk is calling a function on an array: https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/pc/1.8/chunk.js#L62 rather than cycling through it.

**Comment by mhsjlw** [comment]
```
RangeError: Index out of range
    at checkInt (buffer.js:1180:11)
    at Buffer.writeUInt8 (buffer.js:1226:5)
    at sections.(anonymous function).initialize (prismarine-chunk/src/pc/1.8/chunk.js:68:22)
```

Now occurs

**Comment by rom1504** [comment]
fixed
